"""add chat summary

Revision ID: 643a02aac7aa
Revises: 4ec6f09adf0c
Create Date: 2026-07-26 12:52:25.643105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643a02aac7aa'
down_revision: Union[str, Sequence[str], None] = '4ec6f09adf0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'summary_updated_at')
    op.drop_column('chat_sessions', 'summary')
    # ### end Alembic commands ###
