from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from uuid import UUID, uuid4
from datetime import UTC

from app.chunking.models import DocumentChunk


@dataclass(slots=True)
class EmbeddingVector:
    """
    Represents a dense embedding vector generated by an
    embedding model.

    The vector itself is intentionally independent of any
    embedding provider or vector database.
    """

    values: list[float]

    @property
    def dimensions(
        self,
    ) -> int:
        """
        Returns the embedding dimension.
        """

        return len(
            self.values,
        )


@dataclass(slots=True)
class EmbeddingMetadata:
    """
    Metadata describing how an embedding was generated.

    Document metadata is intentionally not duplicated here,
    since it already exists inside DocumentChunk.
    """

    model: str

    dimensions: int

    processing_time_ms: float = 0.0

    cost_usd: float = 0.0

    cached: bool = False

    validated: bool = False

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC),
    )


@dataclass(slots=True)
class EmbeddedChunk:
    """
    Represents a chunk together with its embedding.

    This object is produced by the embedding pipeline and
    becomes the input to the vector database.
    """

    chunk: DocumentChunk

    vector: EmbeddingVector

    metadata: EmbeddingMetadata

    @property
    def chunk_uuid(
        self,
    ) -> UUID | None:
        """
        Returns the chunk UUID.
        """

        return self.chunk.metadata.chunk_uuid

    @property
    def document_uuid(
        self,
    ) -> UUID | None:
        """
        Returns the document UUID.
        """

        return self.chunk.metadata.document_uuid

    @property
    def text(
        self,
    ) -> str:
        """
        Returns the chunk text.
        """

        return self.chunk.text

    @property
    def dimensions(
        self,
    ) -> int:
        """
        Returns the embedding dimensions.
        """

        return self.vector.dimensions


@dataclass(slots=True)
class EmbeddingBatch:
    """
    Represents a batch of chunks sent in a single
    embedding request.
    """

    batch_id: UUID = field(
        default_factory=uuid4,
    )

    chunks: list[DocumentChunk] = field(
        default_factory=list,
    )

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC),
    )

    @property
    def size(
        self,
    ) -> int:
        """
        Returns the number of chunks in the batch.
        """

        return len(
            self.chunks,
        )

    @property
    def chunk_ids(
        self,
    ) -> list[UUID]:
        """
        Returns the UUIDs of all chunks contained
        in the batch.
        """

        return [
            chunk.metadata.chunk_uuid
            for chunk in self.chunks
            if chunk.metadata.chunk_uuid is not None
        ]