from __future__ import annotations

from dataclasses import dataclass

from app.chunking.models import DocumentChunk
from uuid import UUID


@dataclass(slots=True)
class SparseVector:
    """
    Represents a sparse vector generated by the
    sparse encoder.

    Unlike dense vectors, sparse vectors contain
    only the non-zero dimensions.
    """

    indices: list[int]

    values: list[float]

    @property
    def nnz(
        self,
    ) -> int:
        """
        Number of non-zero dimensions.
        """

        return len(
            self.indices,
        )

    def __len__(
        self,
    ) -> int:

        return self.nnz


@dataclass(slots=True)
class SparseEmbeddedChunk:
    """
    Represents a document chunk together with
    its sparse vector.
    """

    chunk: DocumentChunk

    vector: SparseVector

    @property
    def text(
        self,
    ) -> str:

        return self.chunk.text

    @property
    def metadata(
        self,
    ):

        return self.chunk.metadata

    @property
    def chunk_uuid(
        self,
    ):

        return self.chunk.metadata.chunk_uuid

    @property
    def document_uuid(
        self,
    ):

        return self.chunk.metadata.document_uuid


@dataclass(slots=True)
class SparseSearchResult:
    """
    Result returned by sparse retrieval.
    """

    chunk_uuid: UUID

    document_uuid: UUID

    score: float

    text: str

    payload: dict